services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      PYTHONPATH: /app
      PYTHONUTF8: "1"
    volumes:
      - .:/app
    command: python --version
