from __future__ import annotations

from pathlib import Path


def test_accurate_intake_live_diagnostic_runbook_records_staged_protocol() -> None:
    runbook_path = Path("docs/quality/ACCURATE_INTAKE_MVP_LIVE_DIAGNOSTIC_RUNBOOK.md")

    assert runbook_path.exists()

    runbook = runbook_path.read_text(encoding="utf-8-sig")

    required_fragments = [
        "claim scope: `live_diagnostic`",
        "primary CurrentShell product-pages founder gate",
        "operator-shell supporting evidence",
        "Generated live artifacts are local diagnostic evidence, not repo truth",
        "full_suite_live_diagnostic remains blocked",
        "offline replay artifact is present and marked `strict_replay_ready`",
        "Full-Suite Evidence Window",
        "`full_suite_replay_ready`",
        "One strict full-suite artifact is diagnostic evidence only",
        "provider robustness matrix marks `model_inversion_evidence_passed`",
        "--stage full_suite_live_diagnostic --offline-replay-artifact artifacts/accurate_intake_mvp_offline_shadow_replay.json",
        "offline_replay_required",
        "strict_pass_first_attempt",
        "pass_after_retry is not strict evidence",
        "timeout_after_retry remains a blocker",
        "must not claim private self-use approval, product readiness, production/default selection, mutation rollout, or live provider truth ownership",
        "No Tavily/web product truth",
        "No production DB",
        "No shadow/canary",
        "must not claim live-canary approval, Kimi default activation, product readiness, or runtime-web activation",
        "browser_executed=true",
        "`context_live_diagnostic_case_matrix`",
        "plan-only anti-overfit gate",
        "fixed matrix instead of ad hoc easy cases",
        "The matrix must remain offline planning evidence only",
        "compound log-and-modify case",
        "stay_local_self_use",
        "python scripts/run_accurate_intake_mvp_live_diagnostic.py --stage provider_health_smoke",
        "python scripts/run_accurate_intake_mvp_live_diagnostic.py --stage schema_contract_probe",
        "python scripts/run_accurate_intake_mvp_live_diagnostic.py --stage fake_provider_active_runtime_gate",
        "tests/test_accurate_intake_mvp_offline_shadow_replay.py",
        "--stage single_case_live_probe --case-id explicit_item_removal_seeded",
        "--stage single_case_live_probe --case-id exact_item_official_label",
        "--stage single_case_live_probe --case-id bubble_milk_tea_refinement",
        "--stage single_case_live_probe --case-id luwei_bare_to_listed_basket",
        "--stage single_case_live_probe --case-id chinese_chicken_rice_correction_removal_debug",
        "single-profile live run",
        "GrokFast first, Kimi later as a separate replay",
        "Prompt cache policy",
        "static system/tool/schema prefix before dynamic context packets",
        "cached_tokens",
        "Trace Grading Layers",
        "current_turn_context_packet",
        "manager_pass_1_decision",
        "manager_pass_2_synthesis",
        "final_response_basis",
        "python scripts/build_accurate_intake_mvp_live_stage_manifest.py",
        "python scripts/build_accurate_intake_contract_hardening_guard.py",
        "python scripts/build_accurate_intake_mvp_offline_shadow_replay.py",
        "python scripts/build_accurate_intake_mvp_live_robustness_matrix.py",
        "python scripts/build_accurate_intake_mvp_live_cost_summary.py",
        "python scripts/build_accurate_intake_mvp_live_decision_pack.py",
        "python scripts/build_accurate_intake_pre_live_self_use_decision_pack.py",
        "python scripts/build_accurate_intake_mvp_private_self_use_candidate.py",
        "`non_fooddb_manager_tool_contract`",
        "Non-FoodDB Manager tool diagnostics remain app-state only and must not use FoodDB/WebSearch evidence.",
        "artifacts/accurate_intake_mvp_live_diagnostic_provider_health.json",
        "artifacts/accurate_intake_mvp_live_diagnostic_schema_probe.json",
        "artifacts/accurate_intake_mvp_live_diagnostic_fake_runtime_gate.json",
        "artifacts/accurate_intake_mvp_live_diagnostic_seeded_removal.json",
        "artifacts/accurate_intake_mvp_live_diagnostic_exact_item.json",
        "artifacts/accurate_intake_mvp_live_diagnostic_bubble_refinement.json",
        "artifacts/accurate_intake_mvp_live_diagnostic_luwei_basket.json",
        "artifacts/accurate_intake_mvp_live_diagnostic_single_case.json",
        "artifacts/accurate_intake_mvp_live_diagnostic_full_suite.json",
        "artifacts/accurate_intake_mvp_live_stage_manifest.json",
        "artifacts/accurate_intake_mvp_offline_shadow_replay.json",
        "artifacts/accurate_intake_mvp_live_robustness_matrix.json",
        "artifacts/accurate_intake_mvp_live_cost_summary.json",
        "artifacts/accurate_intake_mvp_live_decision_pack.json",
        "artifacts/accurate_intake_mvp_private_self_use_candidate.json",
        "python scripts/build_accurate_intake_mvp_live_stage_manifest.py --output artifacts/accurate_intake_mvp_live_stage_manifest_run_i.json",
        "python scripts/build_accurate_intake_contract_hardening_guard.py --output artifacts/accurate_intake_contract_hardening_guard_run_i.json",
        "python scripts/build_accurate_intake_mvp_offline_shadow_replay.py --stage-manifest artifacts/accurate_intake_mvp_live_stage_manifest_run_i.json --output artifacts/accurate_intake_mvp_offline_shadow_replay_run_i.json",
        "python scripts/build_accurate_intake_mvp_live_robustness_matrix.py --output artifacts/accurate_intake_mvp_live_robustness_matrix_run_i.json",
        "python scripts/build_accurate_intake_mvp_live_cost_summary.py --output artifacts/accurate_intake_mvp_live_cost_summary_run_i.json",
        "python scripts/build_accurate_intake_mvp_live_decision_pack.py --output artifacts/accurate_intake_mvp_live_decision_pack_run_i.json",
        "python scripts/build_accurate_intake_mvp_private_self_use_candidate.py --output artifacts/accurate_intake_mvp_private_self_use_candidate_run_i.json",
        "live full-suite failure unlocks attribution/audit only",
        "live failure alone cannot justify prompt/schema/contract hardening",
        "contract_hardening_debt",
        "legal_flows_broken",
        "holdout_tests_added",
        "token counts are not billing truth",
        "set `cost_unavailable_without_pricing` when token usage exists but no provider-reported cost field is present",
        "billing_truth_source=provider_reported_artifact_fields_only",
        "The upstream runtime gate source is `docs/quality/MANAGER_RUNTIME_GATE_LEDGER.yaml`.",
    ]

    for fragment in required_fragments:
        assert fragment in runbook
