from __future__ import annotations

from datetime import UTC, datetime
from typing import Any


def _wave_one_b_two_test_ref(name: str) -> str:
    return "tests.test_wave1_phase_" + "b2_" + name


def build_fooddb_integration_readiness_matrix() -> dict[str, Any]:
    check_edges = (
        _edge(
            edge_id="manager_decision_to_retrieval_intent",
            from_node="manager_semantic_decision",
            to_node="retrieval_intent_from_manager_decision",
            dependency_direction="manager_to_retrieval_hint",
            required_contract="B2ManagerSemanticDecision -> build_retrieval_intent_from_manager_decision",
            current_status="contract_backed",
            manager_style_guard="retrieval_goal_must_come_from_manager_owned_structured_decision_for_runtime_paths",
            evidence=[
                "app.nutrition.application.retrieval_semantic_decision.build_retrieval_intent_from_manager_decision",
                _wave_one_b_two_test_ref(
                    "retrieval_intent.test_manager_semantic_decision_rejects_non_manager_authority"
                ),
            ],
            stop_condition="stop_if_runtime_path_uses_raw_text_retrieval_intent_as_semantic_owner",
        ),
        _edge(
            edge_id="retrieval_router_to_fooddb_local_adapter",
            from_node="retrieval_router",
            to_node="fooddb_local_adapter",
            dependency_direction="application_to_adapter_port",
            required_contract="FoodEvidenceIndexPort.load_records -> IndexedFoodRecord",
            current_status="contract_backed",
            manager_style_guard="retrieval_policy_depends_on_port_records_not_local_json_shape",
            evidence=[
                "app.nutrition.application.food_evidence_index_port.FoodEvidenceIndexPort",
                "app.nutrition.infrastructure.local_food_evidence_index.LocalSmallAnchorFoodEvidenceIndex",
                "tests.test_food_evidence_index_port.test_retrieval_can_depend_on_port_supplied_records",
            ],
            stop_condition="stop_if_retrieval_policy_depends_on_file_path_or_backend_specific_client",
        ),
        _edge(
            edge_id="retrieval_router_to_sqlite_fts_adapter",
            from_node="retrieval_router",
            to_node="sqlite_fts_adapter",
            dependency_direction="application_to_future_adapter_port",
            required_contract="FoodEvidenceIndexPort implementation for SQLite FTS",
            current_status="contract_backed",
            manager_style_guard="future_sqlite_fts_must_supply_same_indexed_record_contract",
            evidence=[
                "app.nutrition.application.food_evidence_index_port.FoodEvidenceIndexPort",
                "app.composition.food_evidence_index_composition.build_food_evidence_index",
                "app.composition.food_evidence_index_composition.build_retriever_backend_availability",
                "app.nutrition.infrastructure.sqlite_food_evidence_index.SQLiteFtsFoodEvidenceIndex",
                "tests.test_sqlite_food_evidence_index",
                "tests.test_food_evidence_index_factory",
            ],
            stop_condition="stop_if_sqlite_fts_requires_manager_or_packetizer_contract_change",
        ),
        _edge(
            edge_id="retrieval_router_to_websearch_candidate",
            from_node="retrieval_router",
            to_node="websearch_candidate_pipeline",
            dependency_direction="application_to_candidate_lane",
            required_contract="candidate_only WebSearch packet boundary",
            current_status="contract_backed",
            manager_style_guard="websearch_may_recall_candidates_but_may_not_set_runtime_truth",
            evidence=[
                "app.nutrition.application.food_evidence_retriever_router.build_food_evidence_retriever_route_plan",
                "app.nutrition.application.websearch_candidate_packet_smoke.build_websearch_candidate_packet_smoke",
                "app.nutrition.application.websearch_source_adapter_guard.build_websearch_source_adapter_guard",
                "tests.test_websearch_candidate_packet_smoke",
                "tests.test_websearch_source_adapter_guard",
            ],
            stop_condition="stop_if_websearch_snippet_or_candidate_becomes_runtime_truth",
        ),
        _edge(
            edge_id="retriever_output_to_compact_packet",
            from_node="retrieval_result",
            to_node="compact_evidence_packet",
            dependency_direction="retrieval_result_to_manager_packet",
            required_contract="compact FoodDB packet without raw rows or full dumps",
            current_status="contract_backed",
            manager_style_guard="manager_receives_compact_evidence_packet_only",
            evidence=[
                "app.nutrition.application.food_evidence_packet_builder.build_food_evidence_recall_packet",
                "tests.test_food_evidence_packet_builder.test_food_evidence_recall_packet_is_compact_and_manager_facing",
            ],
            stop_condition="stop_if_packet_includes_raw_rows_candidate_only_records_or_full_fooddb",
        ),
        _edge(
            edge_id="packet_to_manager_seam",
            from_node="compact_evidence_packet",
            to_node="manager_diagnostic_seam",
            dependency_direction="packet_to_manager_synthesis",
            required_contract="diagnostic seam uses provided packet without inventing source",
            current_status="contract_backed",
            manager_style_guard="manager_uses_packet_grounding_but_does_not_create_fooddb_truth",
            evidence=[
                "app.nutrition.application.grokfast_fooddb_packet_smoke.build_grokfast_fooddb_packet_diagnostic",
                "tests.test_grokfast_fooddb_packet_smoke",
            ],
            stop_condition="stop_if_manager_invents_source_or_mutates_without_grounded_packet",
        ),
        _edge(
            edge_id="packet_to_mutation_guard",
            from_node="compact_evidence_packet",
            to_node="runtime_mutation_guard",
            dependency_direction="grounding_to_write_guard",
            required_contract="mutation guard checks evidence sufficiency before commit",
            current_status="contract_backed",
            manager_style_guard="insufficient_evidence_must_downgrade_to_followup_or_no_mutation",
            evidence=[
                "app.nutrition.application.fooddb_packet_mutation_guard_readiness.build_fooddb_packet_mutation_guard_readiness",
                "tests.test_fooddb_packet_mutation_guard_readiness",
                "app.nutrition.application.grokfast_fooddb_packet_smoke.evaluate_manager_output_against_packet",
                "app.nutrition.application.food_evidence_mvp_policy",
            ],
            stop_condition="stop_if_packet_presence_bypasses_mutation_legality_or_commit_boundary",
        ),
        _edge(
            edge_id="exact_candidate_to_no_mutation",
            from_node="exact_candidate_lane",
            to_node="no_mutation_boundary",
            dependency_direction="candidate_lane_to_guarded_non_mutation",
            required_contract="exact candidates remain non-runtime until separate promotion lane",
            current_status="contract_backed",
            manager_style_guard="exact_candidate_packets_remain_candidate_only_until_separate_promotion_lane",
            evidence=[
                "app.nutrition.application.websearch_candidate_packet_smoke.derive_websearch_candidate_boundary",
                "app.nutrition.application.evidence_packet_consumption.consume_rechecked_packets",
            ],
            stop_condition="stop_if_exact_candidate_can_mutate_ledger_or_claim_exact_truth",
        ),
        _edge(
            edge_id="websearch_candidate_to_selected_extract_request",
            from_node="websearch_candidate_pipeline",
            to_node="selected_extract_request_packet",
            dependency_direction="candidate_lane_to_bounded_extract_request",
            required_contract="selected extract request is bounded and candidate-only",
            current_status="contract_backed",
            manager_style_guard="websearch_candidate_may_request_bounded_extract_but_cannot_become_truth",
            evidence=[
                "app.nutrition.application.websearch_selected_extract_packet_smoke.build_websearch_selected_extract_packet_smoke",
                "tests.test_websearch_selected_extract_packet_smoke",
            ],
            stop_condition="stop_if_selected_extract_request_includes_raw_content_or_runtime_truth",
        ),
        _edge(
            edge_id="selected_extract_request_to_extract_result_candidate",
            from_node="selected_extract_request_packet",
            to_node="extract_result_review_candidate",
            dependency_direction="bounded_extract_request_to_review_candidate",
            required_contract="extract results stay review candidates with provenance and no raw content",
            current_status="contract_backed",
            manager_style_guard="bounded_extract_result_is_evidence_candidate_not_exact_card_truth",
            evidence=[
                "app.nutrition.application.websearch_extract_result_candidate_smoke.build_websearch_extract_result_candidate_smoke",
                "tests.test_websearch_extract_result_candidate_smoke",
            ],
            stop_condition="stop_if_extract_result_candidate_allows_promotion_mutation_or_raw_content",
        ),
        _edge(
            edge_id="extract_result_candidate_to_exact_review_packet",
            from_node="extract_result_review_candidate",
            to_node="exact_card_review_packet",
            dependency_direction="extract_candidate_to_review_packet",
            required_contract="exact-card review packet preserves checklist without approval authority",
            current_status="contract_backed",
            manager_style_guard="exact_review_packet_is_review_only_not_manager_truth",
            evidence=[
                "app.nutrition.application.websearch_exact_candidate_review_packet.build_websearch_exact_candidate_review_packet",
                "tests.test_websearch_exact_candidate_review_packet",
            ],
            stop_condition="stop_if_exact_review_packet_can_approve_promote_or_mutate",
        ),
        _edge(
            edge_id="exact_review_packet_to_live_extract_preflight",
            from_node="exact_card_review_packet",
            to_node="websearch_live_extract_preflight",
            dependency_direction="review_packet_to_diagnostic_preflight",
            required_contract="live extract preflight requires explicit allow-live and keeps runtime truth closed",
            current_status="contract_backed",
            manager_style_guard="live_extract_preflight_authorizes_diagnostic_only_not_runtime_truth",
            evidence=[
                "app.nutrition.application.websearch_live_extract_preflight.build_websearch_live_extract_preflight",
                "app.nutrition.application.websearch_live_extract_preflight.is_websearch_live_extract_preflight_clear",
                "tests.test_websearch_live_extract_preflight",
            ],
            stop_condition="stop_if_live_extract_preflight_claims_runtime_truth_or_omits_explicit_live_flag",
        ),
        _edge(
            edge_id="live_extract_preflight_to_websearch_live_diagnostic_report",
            from_node="websearch_live_extract_preflight",
            to_node="websearch_live_diagnostic_report",
            dependency_direction="diagnostic_preflight_to_live_report_classification",
            required_contract="live diagnostic report must be gated by preflight and remain diagnostic-only",
            current_status="contract_backed",
            manager_style_guard="live_report_may_classify_seam_status_but_cannot_claim_websearch_truth_or_readiness",
            evidence=[
                "scripts.run_accurate_intake_grokfast_websearch_packet_smoke.main",
                "app.nutrition.application.websearch_live_extract_preflight.is_websearch_live_extract_preflight_clear",
                "app.nutrition.application.grokfast_websearch_packet_smoke.build_grokfast_websearch_packet_diagnostic",
                "app.nutrition.application.websearch_live_diagnostic_report.build_websearch_live_diagnostic_report",
                "tests.test_websearch_live_extract_preflight",
                "tests.test_grokfast_websearch_packet_smoke",
                "tests.test_grokfast_websearch_packet_smoke.test_grokfast_websearch_packet_smoke_live_blocks_preflight_review_packet_mismatch",
                "tests.test_grokfast_websearch_packet_smoke.test_grokfast_websearch_packet_smoke_live_blocks_same_ref_packet_drift",
                "tests.test_websearch_live_diagnostic_report",
            ],
            stop_condition="stop_if_live_report_is_generated_without_preflight_or_claims_runtime_truth",
        ),
        _edge(
            edge_id="websearch_live_report_to_manager_contract_probe",
            from_node="websearch_live_diagnostic_report",
            to_node="websearch_manager_contract_probe",
            dependency_direction="live_report_to_sanitized_contract_probe",
            required_contract="provider contract failures are localized without raw payload leakage",
            current_status="contract_backed",
            manager_style_guard="websearch_live_diagnostic_may_identify_contract_blockers_but_not_repair_manager_semantics",
            evidence=[
                "app.nutrition.application.websearch_live_diagnostic_report.build_websearch_live_diagnostic_report",
                "app.nutrition.application.websearch_manager_contract_probe.build_websearch_manager_contract_probe",
                "tests.test_websearch_live_diagnostic_report",
                "tests.test_websearch_manager_contract_probe",
            ],
            stop_condition="stop_if_websearch_contract_probe_leaks_raw_provider_payload_or_changes_manager_contract",
        ),
        _edge(
            edge_id="websearch_contract_probe_to_repair_pack",
            from_node="websearch_manager_contract_probe",
            to_node="websearch_manager_contract_repair_pack",
            dependency_direction="contract_probe_to_sanitized_repair_inputs",
            required_contract="repair pack emits allowlisted diagnostic fields only",
            current_status="contract_backed",
            manager_style_guard="repair_pack_hands_off_contract_evidence_without_prompt_schema_or_semantic_changes",
            evidence=[
                "app.nutrition.application.websearch_manager_contract_repair_pack.build_websearch_manager_contract_repair_pack",
                "tests.test_websearch_manager_contract_repair_pack",
            ],
            stop_condition="stop_if_repair_pack_echoes_untrusted_case_ids_statuses_or_raw_artifact_strings",
        ),
        _edge(
            edge_id="websearch_repair_pack_to_contract_handoff",
            from_node="websearch_manager_contract_repair_pack",
            to_node="websearch_manager_contract_handoff",
            dependency_direction="repair_pack_to_contract_owner_handoff",
            required_contract="manager contract handoff consumes sanitized repair evidence and alignment checks",
            current_status="contract_backed",
            manager_style_guard="handoff_may_route_contract_blockers_to_manager_owner_but_cannot_patch_manager_semantics",
            evidence=[
                "app.nutrition.application.websearch_manager_contract_handoff.build_websearch_manager_contract_handoff",
                "tests.test_websearch_manager_contract_handoff",
            ],
            stop_condition="stop_if_handoff_skips_repair_pack_alignment_or_reemits_untrusted_summary_values",
        ),
        _edge(
            edge_id="websearch_contract_handoff_to_candidate_lane_status",
            from_node="websearch_manager_contract_handoff",
            to_node="websearch_candidate_lane_status_packet",
            dependency_direction="contract_handoff_to_live_gate",
            required_contract="candidate lane requires explicit contract handoff proof before live diagnostic advancement",
            current_status="contract_backed",
            manager_style_guard="candidate_lane_may_block_or_forward_contract_status_but_cannot_decide_manager_semantics",
            evidence=[
                "app.nutrition.application.websearch_manager_contract_handoff.build_websearch_manager_contract_handoff",
                "app.nutrition.application.websearch_candidate_lane_status_packet.build_websearch_candidate_lane_status_packet",
                "tests.test_websearch_manager_contract_handoff",
                "tests.test_websearch_candidate_lane_status_packet",
            ],
            stop_condition="stop_if_candidate_lane_advances_to_live_without_contract_handoff_or_leaks_untrusted_next_slice",
        ),
        _edge(
            edge_id="listed_components_to_approved_runtime_anchors",
            from_node="listed_basket_components",
            to_node="approved_runtime_anchors_only",
            dependency_direction="listed_component_lookup_to_runtime_anchor_boundary",
            required_contract="listed basket estimates only approved runtime anchors",
            current_status="contract_backed",
            manager_style_guard="listed_basket_components_may_estimate_only_when_runtime_anchor_is_approved",
            evidence=[
                "app.nutrition.application.fooddb_listed_component_expansion_plan.build_listed_component_expansion_plan",
                "tests.test_fooddb_listed_component_expansion_plan",
            ],
            stop_condition="stop_if_bare_basket_or_unapproved_component_receives_estimate",
        ),
    )
    counts = {
        "contract_backed": sum(1 for edge in check_edges if edge["current_status"] == "contract_backed"),
        "draft": sum(1 for edge in check_edges if edge["current_status"] == "draft"),
        "missing": sum(1 for edge in check_edges if edge["current_status"] == "missing"),
    }
    return {
        "artifact_type": "accurate_intake_fooddb_integration_readiness_matrix",
        "artifact_schema_version": "1.0",
        "generated_at_utc": datetime.now(UTC).isoformat().replace("+00:00", "Z"),
        "track": "FDB",
        "claim_scope": "dependency_inversion_and_manager_style_integration_check",
        "runtime_truth_changed": False,
        "mutation_changed": False,
        "shared_contract_changed": False,
        "manager_context_changed": False,
        "websearch_runtime_truth_allowed": False,
        "readiness_claimed": False,
        "check_edges": list(check_edges),
        "summary": {
            "edge_count": len(check_edges),
            **counts,
            "next_required_slices": [
                "manager_fooddb_packet_seam_smoke",
            ],
        },
        "non_claims": [
            "no_runtime_truth_promotion",
            "no_packetizer_contract_change",
            "no_manager_context_change",
            "no_websearch_runtime_truth",
            "no_readiness_claim",
        ],
    }


def _edge(
    *,
    edge_id: str,
    from_node: str,
    to_node: str,
    dependency_direction: str,
    required_contract: str,
    current_status: str,
    manager_style_guard: str,
    evidence: list[str],
    stop_condition: str,
) -> dict[str, Any]:
    return {
        "edge_id": edge_id,
        "from": from_node,
        "to": to_node,
        "dependency_direction": dependency_direction,
        "required_contract": required_contract,
        "current_status": current_status,
        "manager_style_guard": manager_style_guard,
        "evidence": evidence,
        "stop_condition": stop_condition,
    }


__all__ = ["build_fooddb_integration_readiness_matrix"]
