"""Add trace_json to MessageBuffer

Revision ID: 9a1c216a0fda
Revises: 20260418_0002
Create Date: 2026-04-19 04:45:38.702930
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a1c216a0fda'
down_revision = '20260418_0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with op.batch_alter_table('body_plans', schema=None) as batch_op:
        batch_op.alter_column('safety_floor_kcal',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('message_buffer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trace_json', sa.JSON(), nullable=False, server_default='{}'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_buffer', schema=None) as batch_op:
        batch_op.drop_column('trace_json')

    with op.batch_alter_table('body_plans', schema=None) as batch_op:
        batch_op.alter_column('safety_floor_kcal',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
