"""Shared domain models — canonical location.

All cross-cutting domain models live here.  ``app.domain`` re-exports
everything for backward compatibility.
"""

from .conversation_state import (
    AnswerSourceDecision,
    ActiveMealState,
    ActiveMealSummary,
    ConversationArchiveRecord,
    ConversationDigest,
    ConversationMessage,
    ConversationRetrievalHit,
    ConversationState,
    DecisionJournal,
    DurableMemoryHit,
    EvidenceJournal,
    GroundingBundle,
    MealRecord,
    PendingFollowupState,
    ManagerStateDigest,
    RecentTurnSummary,
    RetrievedContextChunk,
    RouteDecision,
    SessionTranscriptRecord,
    SessionSummary,
    TraceDiagnosis,
    TraceEnvelope,
    TraceMeta,
    TraceSpan,
    TraceSummary,
    
)
from .meal_state import CanonicalMealState
from .canonical_models import (
    ActiveBodyPlanView,
    BodyObservation,
    BodyProfile,
    BodyPlan,
    CurrentBudgetMealSummary,
    CurrentBudgetView,
    DayBudgetLedger,
    LedgerEntry,
    MealItem,
    MealThread,
    MealVersion,
    ProactiveTrigger,
    ProposalContainer,
    ProposalOption,
)

__all__ = [
    "AnswerSourceDecision",
    "ActiveMealState",
    "ActiveMealSummary",
    "CanonicalMealState",
    "ConversationArchiveRecord",
    "ConversationDigest",
    "ConversationMessage",
    "ConversationRetrievalHit",
    "ConversationState",
    "DecisionJournal",
    "DurableMemoryHit",
    "EvidenceJournal",
    "GroundingBundle",
    "MealRecord",
    "PendingFollowupState",
    "ManagerStateDigest",
    "RecentTurnSummary",
    "RetrievedContextChunk",
    "RouteDecision",
    "SessionTranscriptRecord",
    "SessionSummary",
    "TraceDiagnosis",
    "TraceEnvelope",
    "TraceMeta",
    "TraceSpan",
    "TraceSummary",
    
    "ActiveBodyPlanView",
    "BodyObservation",
    "BodyProfile",
    "BodyPlan",
    "CurrentBudgetMealSummary",
    "CurrentBudgetView",
    "DayBudgetLedger",
    "LedgerEntry",
    "MealItem",
    "MealThread",
    "MealVersion",
    "ProactiveTrigger",
    "ProposalContainer",
    "ProposalOption",
]
