from __future__ import annotations

from app.composition.accurate_intake_product_pages_renderer_source_map_shared import ROOT


PAGE_SPECS = {
    "chat": {
        "path": ROOT / "static" / "accurate-intake-chat.html",
        "page_id": "accurate-intake-chat-page-v1",
        "surface_role": "chat",
        "selectors": (
            "#chat-scroll",
            "#message-input",
            "#send-button",
            "#chat-history-status",
            "#user-id",
            "#local-date",
            "#chat-day-link",
            "#chat-context-strip",
            "#chat-context-policy",
            "#chat-context-loaded",
            "#chat-context-omitted",
            "#chat-context-pins",
            "#chat-context-targets",
            "#chat-target-candidate-list",
            "#composer",
        ),
        "endpoints": ("/estimate", "/accurate-intake/chat-history"),
        "render_functions": (
            "renderHistory",
            "appendMessage",
            "loadHistory",
            "submitMessage",
            "contextSummaryFromHistory",
            "renderTargetCandidates",
            "renderSessionAndContext",
            "updateNavigationLinks",
            "updateCurrentUrl",
        ),
        "backend_fields": (
            "payload.messages",
            "message.role",
            "message.content",
            "message.context_policy_version",
            "message.loaded_context_summary",
            "message.omitted_context_summary",
            "message.pending_pins_present",
            "message.target_candidate_count",
            "message.target_candidate_names",
            "payload.coach_message",
            "payload.message_count",
            "user_id: userId()",
            "local_date: selectedDate()",
            "allow_search: false",
        ),
    },
    "today": {
        "path": ROOT / "static" / "accurate-intake-today.html",
        "page_id": "accurate-intake-today-page-v1",
        "surface_role": "today-diary",
        "selectors": (
            "#user-id",
            "#selected-date",
            "#previous-day",
            "#next-day",
            "#day-strip",
            "#budget-kcal",
            "#consumed-kcal",
            "#remaining-kcal",
            "#macro-panel",
            "#protein-g",
            "#carbs-g",
            "#fat-g",
            "#macro-guard-reason",
            "#today-status",
            "#meal-list",
            "#chat-link",
        ),
        "endpoints": ("/today/current-budget",),
        "render_functions": (
            "renderDayStrip",
            "renderMeals",
            "renderBudgetSummary",
            "renderMacroPanel",
            "loadToday",
            "writeText",
            "updateNavigationLinks",
            "updateCurrentUrl",
        ),
        "backend_fields": (
            "payload.budget_kcal",
            "payload.consumed_kcal",
            "payload.remaining_kcal",
            "payload.consumed_protein",
            "payload.consumed_carbs",
            "payload.consumed_fat",
            "payload.show_macro",
            "payload.macro_guard_reason",
            "payload.meals",
            "payload.status",
            "meal.meal_title",
            "meal.occurred_at",
            "meal.resolution_status",
            "meal.total_kcal",
        ),
    },
    "body": {
        "path": ROOT / "static" / "accurate-intake-body.html",
        "page_id": "accurate-intake-body-page-v1",
        "surface_role": "body-plan",
        "selectors": (
            "#body-plan-summary",
            "#plan-daily-target",
            "#plan-tdee",
            "#plan-current-weight",
            "#plan-target-weight",
            "#plan-activity",
            "#plan-goal",
            "#body-budget-loop",
            "#body-active-target",
            "#body-consumed-kcal",
            "#body-remaining-kcal",
            "#body-estimated-deficit",
            "#body-effective-budget",
            "#body-weekly-progress",
            "#body-status",
            "#weight-form",
            "#weight-kg",
            "#onboarding-form",
            "#manual-target-form",
            "#manual-daily-target",
            "#weight-history",
        ),
        "endpoints": (
            "/body-plan/active",
            "/weight/observations",
            "/weight/observation",
            "/onboarding/bootstrap",
            "/body-plan/manual-daily-target",
            "/today/deficit-summary",
            "/today/effective-budget",
            "/today/weekly-progress",
        ),
        "render_functions": (
            "renderPlan",
            "renderWeights",
            "renderBudgetReadModels",
            "loadBudgetReadModels",
            "loadBody",
            "writeText",
            "requestJson",
            "updateNavigationLinks",
            "updateCurrentUrl",
        ),
        "backend_fields": (
            "plan.plan_status",
            "plan.daily_budget_kcal",
            "plan.recommended_target_kcal",
            "plan.estimated_tdee",
            "plan.current_weight_kg",
            "plan.target_weight_kg",
            "plan.activity_level",
            "plan.goal_type",
            "payload.observations",
            "payload.weight_kg",
            "payload.active_body_plan",
            "payload.target_kcal",
            "payload.current_budget?.budget_kcal",
            "deficit.active_daily_target_kcal",
            "deficit.consumed_kcal",
            "deficit.remaining_kcal",
            "deficit.estimated_daily_deficit_kcal",
            "effective.runtime_effective_budget_kcal",
            "weekly.total_consumed_kcal",
            "weekly.estimated_weekly_deficit_kcal",
        ),
    },
}


__all__ = ["PAGE_SPECS"]
