from __future__ import annotations

from typing import Any

from app.composition.body_budget_calibration_readiness_proposal_models import (
    build_calibration_proposal_read_models,
)


def build_body_budget_stable_read_models() -> list[dict[str, Any]]:
    return [
        *_body_budget_read_models(),
        *build_calibration_proposal_read_models(),
    ]


def _body_budget_read_models() -> list[dict[str, Any]]:
    return [
        {
            "name": "current_budget_view",
            "aliases": [],
            "canonical_name_required_for_current_shell": True,
            "backend_route": "/today/current-budget",
            "read_function": "app.composition.current_budget_read_model.build_current_budget_view",
            "truth_owner": ["budget", "intake"],
            "stable_fields": [
                "budget_kcal",
                "consumed_kcal",
                "adjustment_kcal",
                "remaining_kcal",
                "active_meal_count",
                "meals",
                "show_macro",
                "macro_guard_reason",
                "last_recomputed_at",
            ],
            "current_shell_allowed_use": "render_supplied_values_only",
            "current_shell_forbidden": [
                "recompute_consumed",
                "recompute_remaining",
                "recompute_adjustment_sign",
                "derive_macro_visibility",
            ],
        },
        {
            "name": "body_budget_deficit_summary",
            "aliases": ["deficit_summary"],
            "canonical_name_required_for_current_shell": True,
            "backend_route": "/today/deficit-summary",
            "read_function": "app.composition.body_budget_deficit_summary.build_body_budget_deficit_summary",
            "truth_owner": ["body", "budget", "composition_read_model"],
            "stable_fields": [
                "source_kind",
                "read_only",
                "truth_owner",
                "target_available",
                "target_source",
                "active_daily_target_kcal",
                "recommended_target_kcal",
                "consumed_kcal",
                "adjustment_kcal",
                "remaining_kcal",
                "estimated_daily_deficit_kcal",
                "latest_weight_kg",
                "latest_weight_observed_at",
                "latest_weight_observation_id",
                "weight_history_count",
                "current_budget",
                "active_body_plan",
            ],
            "current_shell_allowed_use": "render_deficit_observation_loop_from_backend_values",
            "current_shell_forbidden": [
                "calculate_tdee",
                "calculate_target_kcal",
                "calculate_remaining_kcal",
                "calculate_estimated_deficit",
                "select_latest_weight",
                "infer_target_source_legality",
            ],
        },
        {
            "name": "body_budget_weekly_progress",
            "aliases": [],
            "canonical_name_required_for_current_shell": True,
            "backend_route": "/today/weekly-progress",
            "read_function": "app.composition.body_budget_weekly_progress.build_body_budget_weekly_progress",
            "truth_owner": ["body", "budget", "composition_read_model"],
            "stable_fields": [
                "source_kind",
                "read_only",
                "window_start_date",
                "window_end_date",
                "window_days",
                "days",
                "logged_day_count",
                "target_available_day_count",
                "total_consumed_kcal",
                "total_remaining_kcal",
                "estimated_weekly_deficit_kcal",
                "weight_observation_count",
                "first_weight_kg",
                "latest_weight_kg",
                "weight_delta_kg",
                "weight_delta_policy",
            ],
            "current_shell_allowed_use": "render_weekly_deficit_and_weight_loop_from_backend_values",
            "current_shell_forbidden": [
                "compute_weekly_deficit",
                "compute_weight_delta",
                "compute_logged_day_coverage",
                "infer_trend",
                "infer_calibration_eligibility",
                "infer_rescue_behavior",
                "infer_recommendation_behavior",
                "infer_proactive_behavior",
            ],
        },
        {
            "name": "body_budget_effective_budget_view",
            "aliases": [],
            "canonical_name_required_for_current_shell": True,
            "backend_route": "/today/effective-budget",
            "read_function": "app.composition.body_budget_effective_budget.build_body_budget_effective_budget_view",
            "truth_owner": ["budget", "composition_read_model"],
            "stable_fields": [
                "source_kind",
                "read_only",
                "truth_owner",
                "ledger_present",
                "base_budget_kcal",
                "consumed_kcal",
                "runtime_adjustment_total_kcal",
                "runtime_effective_budget_kcal",
                "remaining_kcal",
                "remaining_formula",
                "adjustment_layers",
                "adjustment_layers.signed_effective_budget_delta_kcal",
                "adjustment_layers.runtime_adjustment_total_from_entries_kcal",
                "entry_breakdown",
                "sign_policy",
                "calibration_adjustment_ledger_entry_enabled",
            ],
            "current_shell_allowed_use": "render_effective_budget_layers_and_sign_policy_from_backend_values",
            "current_shell_forbidden": [
                "calculate_effective_budget",
                "calculate_adjustment_layer_totals",
                "calculate_sign_policy",
                "infer_calibration_adjustment_ledger_entry_readiness",
                "reinterpret_signed_layers_outside_backend_budget_math_helper",
            ],
        },
        {
            "name": "active_body_plan_view",
            "aliases": [],
            "canonical_name_required_for_current_shell": True,
            "backend_route": "/body-plan/active",
            "read_function": "app.body.application.active_body_plan_read_model.build_active_body_plan_view",
            "truth_owner": ["body"],
            "stable_fields": [
                "body_plan_id",
                "plan_status",
                "goal_type",
                "current_weight_kg",
                "target_weight_kg",
                "daily_budget_kcal",
                "recommended_target_kcal",
                "daily_deficit_kcal",
                "safety_floor_kcal",
                "estimated_tdee",
                "target_pace_kg_per_week",
                "plan_source",
                "profile_status",
                "last_updated_at",
            ],
            "current_shell_allowed_use": "render_active_body_plan_backend_values",
            "current_shell_forbidden": [
                "run_bmr_formula",
                "run_tdee_formula",
                "infer_manual_override_legality",
                "treat_profile_weight_as_latest_observation",
            ],
        },
    ]


__all__ = ["build_body_budget_stable_read_models"]
